In [1]:
pip install -U keras

Requirement already up-to-date: keras in /usr/local/lib/python3.6/dist-packages (2.3.1)


In [2]:
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, LSTM, Dense, Dropout,GRU , Flatten,Input,Activation
from keras.preprocessing.text import Tokenizer
import pandas as pd
import numpy as np 
import keras.utils as ku
from keras.models import Sequential
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [0]:
df= pd.read_csv("SMSSpam.csv",sep='\t',header=None, error_bad_lines=False)

In [4]:
df = df.rename(  columns={0: "label", 1: "msg"})    # Rename Header
df

label                                                msg
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   5572 non-null   object
 1   msg     5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [0]:
df["label"] = df["label"].astype('category')

In [0]:
df["label"] = df["label"].cat.codes

In [8]:
df

label                                                msg
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
msg_list = list(df.msg.values)
len(msg_list)

5572

In [0]:
import string, os
def clean_text(txt):
    txt = "".join(v for v in txt if v not in string.punctuation).lower()
    txt = txt.encode("utf8").decode("ascii",'ignore')
    return txt

In [0]:
corpus = [clean_text(x) for x in msg_list]

In [12]:
corpus[:10]

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s',
 'u dun say so early hor u c already then say',
 'nah i dont think he goes to usf he lives around here though',
 'freemsg hey there darling its been 3 weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send 150 to rcv',
 'even my brother is not like to speak with me they treat me like aids patent',
 'as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune',
 'winner as a valued network customer you have been selected to receivea 900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only',
 'had your mobile 11 months or more u r entitled to update to 

In [13]:
token = []
for i in corpus:
  token.append(i.split(" "))
len(token)

5572

In [14]:
# Maximum Length of String

max2 = len(max(token, key=len))
print(max2)

171


In [15]:
token[:2]

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni']]

In [0]:
for i in range(len(token)):
  for j in range(len(token[i])):
    if len(token[i])<max2:
      c = max2-len(token[i])
      for k in range(c):
        token[i].append("Null")


In [17]:
token[0][22]

'Null'

In [18]:
pip install --upgrade gensim

Requirement already up-to-date: gensim in /usr/local/lib/python3.6/dist-packages (3.8.1)


In [0]:
import gensim 
from gensim.models import Word2Vec 

In [0]:
model_vec = Word2Vec(token , size=150)

In [21]:
words = list(model_vec.wv.vocab)
print(len(words))

1831


In [22]:
model_vec['hot']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.09482092, -0.01584643,  0.22728445, -0.15311421, -0.132205  ,
       -0.17973043,  0.02455102,  0.15952337,  0.10667264, -0.11542536,
       -0.11910083,  0.13905571, -0.00536266, -0.06888712,  0.10106509,
       -0.0237592 ,  0.0842792 ,  0.06422084, -0.09491048, -0.04777528,
       -0.16265707, -0.05477571,  0.07646436,  0.01919821,  0.23431674,
       -0.02557178, -0.15772995,  0.16725473,  0.09725241, -0.27111503,
       -0.04189689, -0.10961535,  0.01633514,  0.11654013, -0.08180158,
       -0.04963827, -0.21312848,  0.15141486,  0.02892336,  0.01654593,
        0.14274947, -0.1092276 ,  0.26046365, -0.11377522, -0.02715309,
       -0.15226363,  0.17946726, -0.01963009,  0.0741913 ,  0.1888013 ,
        0.03675045, -0.14591813, -0.11740346, -0.08268819,  0.0922442 ,
       -0.12982276, -0.03226266,  0.03970668,  0.01167979,  0.05551351,
       -0.22173436, -0.22531398, -0.02791993,  0.10542528,  0.14403582,
        0.07414305,  0.151912  ,  0.11039618, -0.05165114, -0.03

In [23]:
len(token)

5572

In [0]:
embed = np.zeros((len(token),max2,150) ,dtype = np.float32)   # Embedded Word Matrix

In [0]:
for i in range (len(corpus)):
  a = corpus[i].split(" ")
  for j in range(len(a)):
    try:
      embed[i,j] = model_vec.wv[a[j]]
    except (KeyError):
      #print(i,j)
      embed[i,j] = model_vec.wv['Null']
      pass
    

In [26]:
model_vec.wv['Null']

array([-0.33347267,  0.4148582 , -1.0443904 ,  1.507119  , -0.08109762,
        0.17388543,  0.4695774 ,  0.03464308, -0.52517927,  1.4613428 ,
        1.2094736 , -0.7857763 , -0.39214864, -1.632768  , -0.26831704,
        0.494829  ,  1.287062  ,  0.16967435,  0.00747477,  0.47027868,
        0.15711215, -0.32841703, -0.71573246, -0.23891693, -1.2609345 ,
        0.8339545 , -0.09980703, -1.6104051 , -0.72490764,  1.0257984 ,
        0.7725477 , -1.7245588 ,  0.56488127, -1.08686   ,  0.7204086 ,
       -0.24662364,  1.1934808 , -0.9030578 ,  1.4621586 , -0.10785769,
       -1.1357414 ,  1.3071914 , -1.0659937 ,  0.5098446 ,  0.10568626,
        1.7432134 , -0.89693284, -0.5890937 , -0.3856214 , -0.9576697 ,
       -1.5396255 ,  0.52585006,  1.1439235 ,  0.8632741 , -0.48574376,
        1.2838998 , -0.10133138, -0.46792683,  0.212716  , -1.1566164 ,
       -0.60888904,  0.797638  , -0.42328483, -0.9760919 , -1.0628892 ,
       -0.46231773, -1.7848186 , -0.9034262 , -0.35912886,  1.36

In [0]:
y = df.label.values
y = y.reshape(-1,1)

x_train, x_test, y_train, y_test = train_test_split(embed, y, test_size=0.30, random_state=42)

In [28]:
x_train[0].shape

(171, 150)

In [29]:
embed.shape

(5572, 171, 150)

In [30]:
len(words)

1831

In [0]:
model = Sequential()
model.add(LSTM(150 ,return_sequences=True , dropout = 0.3))   
model.add(Dense(units=len(words)))
model.add(LSTM(64, dropout = 0.2))
model.add(Dense(1,activation='sigmoid'))

In [0]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 171, 150)          180600    
_________________________________________________________________
dense_1 (Dense)              (None, 171, 1831)         276481    
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                485376    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 942,522
Trainable params: 942,522
Non-trainable params: 0
_________________________________________________________________


In [35]:
for layer in model.layers:
  print(layer.input_shape)
  print(layer.output_shape)
  print("___________")

(None, 171, 150)
(None, 171, 150)
___________
(None, 171, 150)
(None, 171, 1831)
___________
(None, 171, 1831)
(None, 64)
___________
(None, 64)
(None, 1)
___________


In [34]:
model.fit(x_train, y_train,epochs=15,validation_data=(x_test, y_test) ,verbose=1)

Train on 3900 samples, validate on 1672 samples
Epoch 1/15
3900/3900 [==============================] - 153s 39ms/step - loss: 0.4114 - accuracy: 0.8659 - val_loss: 0.3943 - val_accuracy: 0.8660
Epoch 2/15
3900/3900 [==============================] - 150s 38ms/step - loss: 0.3953 - accuracy: 0.8659 - val_loss: 0.3950 - val_accuracy: 0.8660
Epoch 3/15
3900/3900 [==============================] - 150s 38ms/step - loss: 0.3947 - accuracy: 0.8659 - val_loss: 0.3954 - val_accuracy: 0.8660
Epoch 4/15
3900/3900 [==============================] - 152s 39ms/step - loss: 0.3952 - accuracy: 0.8659 - val_loss: 0.3940 - val_accuracy: 0.8660
Epoch 5/15
3900/3900 [==============================] - 148s 38ms/step - loss: 0.3944 - accuracy: 0.8659 - val_loss: 0.3976 - val_accuracy: 0.8660
Epoch 6/15
3900/3900 [==============================] - 146s 38ms/step - loss: 0.3961 - accuracy: 0.8659 - val_loss: 0.3944 - val_accuracy: 0.8660
Epoch 7/15
3900/3900 [==============================] - 151s 39ms/step

In [37]:
score, acc = model.evaluate(x_test, y_test ,verbose=1)
print('Test score:', score)
print('Test accuracy:', acc)

1672/1672 [==============================] - 14s 8ms/step
Test score: 0.3940693359625967
Test accuracy: 0.8660287261009216


In [40]:
model_vec.wv.most_similar("i")

[('how', 0.7780188322067261),
 ('me', 0.7779303193092346),
 ('ya', 0.7746725082397461),
 ('lmao', 0.7735095024108887),
 ('much', 0.7581934332847595),
 ('they', 0.757047712802887),
 ('holla', 0.755517303943634),
 ('hmmm', 0.7493034601211548),
 ('it', 0.7462847828865051),
 ('well', 0.7453324198722839)]

In [38]:
p = x_test[-2].reshape(1,171,-1)
model.predict_classes(p)

array([[0]], dtype=int32)

In [39]:
y_test[-2]

array([1], dtype=int8)